### PR TITLE
Exit on gofmt warnings

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by yorinasub17** [comment]
Thanks for your contribution! However, IIRC, `pre-commit` checks for files that were modified to fail the hook, so it shouldn't be necessary to do this. In fact, the current implementation is arguably better because it will leave the files in a state that you can just check in to resolve the `pre-commit` issues.

Do you have a test case or use case where this is not the behavior you are seeing (files that were not `go fmt`-ed failing the pre-commit check)?

**Comment by gliptak** [comment]
```terratest``` has ```gofmt``` warnings https://goreportcard.com/report/github.com/gruntwork-io/terratest

I submitted https://github.com/gruntwork-io/terratest/pull/426 to check current behaviour

**Comment by yorinasub17** [comment]
Thanks for reporting that, but that looks like it is run with the simplify flag. We don't use the simplify flag as it does a few more aggressive edits that can be incompatible with third party library.

I would suggest creating a new pre-commit hook that runs `gofmt -s` for the use cases that want to use that.

**Comment by gliptak** [comment]
@yorinasub17 would excluding ```vendor```/```etc``` allow to run strict checking?

**Comment by yorinasub17** [comment]
No, because the problem isn't running it against the vendor libraries (in fact, it is already excluded by the hook), but rather the edits themselves could break the library. Also, because `gofmt -s` is also sentitive to the go version used to run it, it's not "safe" to run on library code that should support as wide range of go versions as possible.

As an aside, this makes sense to have if the goal of the project is to achieve a perfect score on the go report card, but quite frankly that is a practically difficult task to achieve and as such is not something we strive for.

**Pull request closed without merging**
