### PR TITLE
Increase bash script portability

### PR DESCRIPTION
**Pull request by alias-dev**
Fixes "Executable `/bin/bash` not found" on NixOS systems

### CODE REVIEW

**Comment by infraredgirl** [comment]
Looks like the CI build is failing on an unrelated issue. I opened a PR to fix it: https://github.com/gruntwork-io/pre-commit/pull/55.

**Comment by infraredgirl** [comment]
Hey @alias-dev, the above PR has been merged. Could you pull the latest master?

**Comment by alias-dev** [comment]
Thanks @infraredgirl, that's now updated

**Review by infraredgirl — APPROVED** [review]
LGTM, thanks for the contribution!

**Pull request merged**
