### PR TITLE
Add support to use args in tflint

### PR DESCRIPTION
**Pull request by msgongora**
## Description
While I was trying to disable some rules for tflint at specific locations I realized that I needed to use `args` because having a .tflint.hcl wasn't an option for my project structure. Here is the support for args.
```console
$ tflint -v
TFLint version 0.44.1
+ ruleset.terraform (0.2.2-bundled)

$ tf version
Terraform v1.3.8
```

```yaml
  - id: tflint
    name: Terraform lint (gcp project level)
    files: ^gcp/[\w_\-]+/[\w_\-]+\.tf$
    args: [--disable-rule=terraform_required_providers]
```

## TODOs

Please ensure all of these TODOs are completed before asking for a review.

- [x] Ensure the branch is named correctly with the issue number. e.g: `feature/new-vpc-endpoints-955` or `bug/missing-count-param-434`.
- [x] Update the docs.
- [x] Keep the changes backward compatible where possible.
- [x] Run the pre-commit checks successfully.
- [x] Run the relevant tests successfully.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.

## Related Issues
Not my initial issue but #90 should be fixed with this code.

### CODE REVIEW

**Review by gcagle3 — DISMISSED** [review]
Tested locally against tflint versions v0.39.3, v0.40.0, v0.43.0, v0.45.0, and v0.46.0. Confirming that this works as expected. 

With the following, you can correctly use this change to pass a "--filter" argument to newer versions of tflint (v0.45.0+) to resolve the deprecation warning discussed in #90:

```
- id: tflint
  args: [--filter]
```

Change is backwards compatible with older versions of tflint.

**Review by j-collier — DISMISSED** [review]
This works perfectly for me as well

**Comment by gcagle3** [comment]
@msgongora It looks like the build is failing because your fork is missing some updated pipeline changes from commit 5341f388c2a962d3bc66e075f00b80ab45b15f24. Could you rebase and pull in the latest changes into your fork? That should resolve the build failure and allow this to proceed.

**Comment by msgongora** [comment]
> @msgongora It looks like the build is failing because your fork is missing some updated pipeline changes from commit [5341f38](https://github.com/gruntwork-io/pre-commit/commit/5341f388c2a962d3bc66e075f00b80ab45b15f24). Could you rebase and pull in the latest changes into your fork? That should resolve the build failure and allow this to proceed.

 ✅

**Review by gcagle3 — APPROVED** [review]
@msgongora thanks for the quick turnaround. Looks like the tests are passing now, so we can move forward with merging this. Thanks again for the great PR!

**Pull request merged**
